services:
  fliplet-backend:
    build:
      context: .
    depends_on:
      fliplet-postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fliplet-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8000"
    networks:
      - fliplet-network

  fliplet-postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - fliplet-postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    networks:
      - fliplet-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  fliplet-postgres-data:

networks:
  fliplet-network:
    driver: bridge
