server:
  port: 8000

spring:
  application:
    name: backend
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:test@example.com}
    password: ${SMTP_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  output.ansi.enabled: ALWAYS

yc:
  s3:
    bucket: fliplet
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
    host: storage.yandexcloud.net
  avatars:
    allowedContentTypes: image/jpg,image/jpeg,image/png,image/webp
    keyPrefix: avatars

logging:
  level:
    root: WARN
    dev.matvenoid.backend: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ./logs/app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{1}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n"

jwt:
  secret: ${JWT_SECRET:test-secret}
  access-token-expiration-ms: 1800000
  refresh-token-expiration-ms: 2592000000

email:
  verification-code-expiration-minutes: 15

app:
  mail:
    verification:
      subject: Подтверждение регистрации на Fliplet

