server:
  port: 8000

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://fliplet-postgres:5432/fliplet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: fliplet-redis
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: matvenoid@gmail.com
    password: smukvemmydhchbcs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  output.ansi.enabled: ALWAYS

logging:
  level:
    root: WARN
    dev.matvenoid.backend: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ./logs/app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{1}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger - %msg%n"

jwt:
  secret: diqe0NzdgoCU/HKyv3RG9gmVmgRvvz2b1EOXUlIk1jvnp3upWmpo/ihv6jrGmucRlcwHnjybBjX3jnUdkxCSFQ==
  access-token-expiration-ms: 1800000
  refresh-token-expiration-ms: 2592000000

email:
  verification-code-expiration-minutes: 1

app:
  mail:
    verification:
      subject: Подтверждение регистрации на Fliplet

